### ISSUE TITLE
ciao_emacs/elisp/ciao-site-file.el is missing because batch-update-autoloads is not defined

### ISSUE THREAD

**Issue by vcholak** [ciao-lang/ciao_emacs#1]
While installing Ciao using this command: 
curl https://ciao-lang.org/boot -sSfL | sh (accepted all defaults)
there is an error below:

Error: void-function (batch-update-autoloads)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0xd25b00b96512f81>))
  debug-early-backtrace()
  debug-early(error (void-function batch-update-autoloads))
  batch-update-autoloads()
  command-line-1(("--eval" "(setq generated-autoload-file \"/Users/vcholak/.ciaoroot/v1.22.0-m7/ciao_emacs/elisp/ciao-site-file.el\")" "-f" "batch-update-autoloads" "."))
  command-line()
  normal-top-level()
Symbol’s function definition is void: batch-update-autoloads

This causes Ciao mode in Emacs not working when opening *.pl files.

Detected OS: DARWIN
Detected architecture: aarch64
The options for this installation are:

   Selected release... v1.22.0-m7 (stable)
   Full development environment... yes
   Use prebuilt binaries... no
   Use prebuilt docs... yes
   Documentation generation... no
   Installation root... /Users/vcholak/.ciaoroot/v1.22.0-m7

**Comment by thierrymarianne** [comment]
Hi! 

You might want to have a look at https://github.com/ciao-lang/ciao/issues/86
and also this patch proposal: 
https://github.com/ciao-lang/ciao/pull/87/files

**Comment by jfmc** [comment]
(Thanks! Fixed with your patch https://github.com/ciao-lang/ciao/commit/90530f72268cab07595d16e6bc3940608738e992)
